name: Publish to the Ballerina central

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Select environment
        required: true
        options:
          - CENTRAL
          - DEV CENTRAL
          - STAGE CENTRAL
      release_version:
        type: string
        description: Enter the release version
        required: true
      org:
        type: string
        description: Enter the organization name
        required: true

jobs:
  publish-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ballerina-platform/setup-ballerina@v1
        name: Install Ballerina
        with:
          version: 2201.7.0
      - name: Pull EDI Tool
        run: bal tool pull edi
      - name: Generate Ballerina Source code
        run: |
          string_list=("finance" "logistics" "manufacturing" "retail" "services" "shipping" "supplychain")
          for item in "${string_list[@]}"; do
              echo "$item"
              bal edi libgen -O ${{ inputs.org }} -n $item -s "$item/schemas" -o "$item/target"
          done
      - name: install 2201.6.0
        run: sudo bal dist pull 2201.6.0
        working-directory: finance
      - name: pack
        run: |
          string_list=("finance" "logistics" "manufacturing" "retail" "services" "shipping" "supplychain")
          current_path="$PWD"
          for item in "${string_list[@]}"; do
              sed -i "s/version = \"[^\"]*\"/version = \"$ release_version\"/" "$current_path/$item/target/$item/Ballerina.toml"
              cd "$current_path/$item/target/$item"
              bal pack
          done
        working-directory:
      - name: push
        env:
          BALLERINA_CENTRAL_ACCESS_TOKEN: ${{ secrets.BALLERINA_CENTRAL_ACCESS_TOKEN }}
        run: |
          string_list=("finance" "logistics" "manufacturing" "retail" "services" "shipping" "supplychain")
          current_path="$PWD"
          for item in "${string_list[@]}"; do
            cd "$current_path/$item/target/$item"
            bal push
          done
